### ISSUE TITLE
Error running Intelligent MIDI Comparator Gradio App app.py

### ISSUE THREAD

**Issue by SoftologyPro** [asigalov61/Giant-Music-Transformer#1]
When I try and run `app.py` under `Intelligent MIDI Comparator Gradio App` I get the error

```
Traceback (most recent call last):
  File "D:\Tests\Giant Music Transformer\Giant-Music-Transformer\Gradio\Intelligent MIDI Comparator Gradio App\app.py", line 20, in <module>
    from midi_to_colab_audio import midi_to_colab_audio
  File "D:\Tests\Giant Music Transformer\Giant-Music-Transformer\Gradio\Intelligent MIDI Comparator Gradio App\midi_to_colab_audio.py", line 1812, in <module>
    raise ImportError("Couldn't find the FluidSynth library.")
ImportError: Couldn't find the FluidSynth library.
```

`pip list` shows I installed fluidsynth
`fluidsynth         0.2`

Any ideas how to fix?  Also will there be a gradio app for the text to midi?

**Comment by asigalov61** [comment]
@SoftologyPro Thank you for reporting issues :)

You need to install FluidSynth package:

Try:

```
!sudo apt install fluidsynth
```

**Comment by asigalov61** [comment]
@SoftologyPro As far as text-to-midi, I have the text-to-midi implementation here:

https://github.com/asigalov61/Text-to-Music-Transformer

**Comment by asigalov61** [comment]
@SoftologyPro I realized that you may be on Windows:

Try fluidsynth instructions installation from here:

https://github.com/asigalov61/Allegro-Music-Transformer/tree/main/Local%20Python

**Comment by SoftologyPro** [comment]
> @SoftologyPro Thank you for reporting issues :)
> 
> You need to install FluidSynth package:
> 
> Try:
> 
> ```
> !sudo apt install fluidsynth
> ```

OK, I am on Windows.
So I need to do more than just `pip install fluidsynth` ?

**Comment by asigalov61** [comment]
@SoftologyPro Yes, if you are on windows you need chocolatey:

https://github.com/asigalov61/Allegro-Music-Transformer/tree/main/Local%20Python

**Comment by SoftologyPro** [comment]
> @SoftologyPro Yes, if you are on windows you need chocolatey:
> 
> https://github.com/asigalov61/Allegro-Music-Transformer/tree/main/Local%20Python

That is the only way?  Installing chocolatey and running the install script needs admin rights and script execution enabled.

I am trying to add support for Giant Music Transformer to Visions of Chaos.  Having to ask users to enable these secruities that should be off for safety is annoying.

What does installing via chocolatey do that pip install does not?

I see in the comments
`!apt install fluidsynth #Pip does not work for some reason. Only apt works`

**Comment by asigalov61** [comment]
@SoftologyPro Yes, Windows is hard to work with when it comes to linux packages and yes it does indeed need security changes which sucks, I know...

There are two more options you have:

Either disable fluidsynth/midi_to_colab_audio or search GitHub for more Windows friendly MIDI synthesizer. I think there are some new ones available now...

Sorry I can't be of more help here...

**Comment by asigalov61** [comment]
@SoftologyPro If you will find compatible Windows MIDI synthesizer, please let me know. I need it too and I can help implement it.

Thanks.

**Comment by asigalov61** [comment]
@SoftologyPro I checked and in order to run GMT you only need to install chocolatey and then fluidsynth. There is no need to change Windows permissions for GMT because it does not use pyfluidsynth. GMT uses midi_to_colab_audio module that does not require admin Windows permissions.

Try it out.

**Comment by asigalov61** [comment]
Closing this for now...
